In [1]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [2]:
np.save('myarray',arr)
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
myarray

NameError: name 'myarray' is not defined

In [6]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [7]:
arr1 = np.load('myarray.npy')

## 

In [8]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1

array([0, 1, 2, 3, 4])

In [10]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [11]:
arr_archive = np.load('ziparray.npz')

In [12]:
arr_archive

In [13]:
arr_archive['x']

array([0, 1, 2, 3, 4])

In [14]:
arr_archive['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.array([[1,2,3],[4,5,6]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [19]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])