In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 0.68584344,  1.39236171, -1.48286497, -1.66700753, -1.42918401,
       -0.17798057, -2.2322381 ,  1.45366439,  0.00464968, -1.65332069])

In [6]:
np.add(A,B)

NameError: name 'B' is not defined

In [7]:
B = np.random.randn(10)
B

array([-1.24702954, -0.65449937,  0.12473675, -0.91766848, -0.5400665 ,
       -0.30144966, -0.30706186, -2.57345085,  0.6269544 ,  0.24673687])

In [9]:
np.maximum(A,B)

array([ 0.68584344,  1.39236171,  0.12473675, -0.91766848, -0.5400665 ,
       -0.17798057, -0.30706186,  1.45366439,  0.6269544 ,  0.24673687])

In [10]:
website = 'http://geekluv.com'